<div class="block">
    <div class="blocktitle">
        Client Download
    </div>
    <div class="blockbody">
        <p>To download the client, please follow these steps:</p>
        <ol>
            <li>Download the client <a href="magnet:?xt=urn:btih:7b4f3c64f5623002130cacbdccd5c56bf9d4bd0b&dn=City+Of+Heroes">from here</a> or directly with this magenet link: magnet:?xt=urn:btih:7b4f3c64f5623002130cacbdccd5c56bf9d4bd0b&dn=City+Of+Heroes.</li>
            <li>Extract it somewhere convenient.</li>
            <li>Run "AurorisCOH.bat" and login with the account created above.</li>
        </ol>
        <p>If you already have the SCORE client downloaded, you can instead launch with the following command line:
<pre>start .\score.exe -auth 98.195.28.185 -patchdir score
        -noversioncheck -project "coh"</pre></p>
    </div>
</div>